### ISSUE TITLE
Check for QGIS has hard-coded Windows path

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-geoprocessor-python#108]
The system information checks for QGIS installation.  The folder is currently hard-coded assuming only Windows.  This logic needs to be changed to be specific to the operating system.  For now it would be OK to only do the check for Windows and later can add Linux once we have experience with that.

**Comment by jurentie** [comment]
Steve has improved the system information to be applicable to Cygwin/Linux
