### ISSUE TITLE
File / Open / Command File menu is not working correctly

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-geoprocessor-python#171]
I may have broken something but testing the UI showed inconsistent behavior.  Selecting from the list of previous command files opened a different command file.  It appears that the menu event handling was not synchronized with the command file history.  There were some that were not being handled, for example if the command history file was empty.  It is also unclear that common use cases are handled, such as warning the user to save unsaved command edits before opening a command file.  These issues need to be discussed and resolved.

**Comment by jurentie** [comment]
It looks like there was a typo in the following line of code:
`lambda checked, filename=command_file: self.ui_action_open_command_file(command_file))`
which should have been:
`lambda checked, filename=command_file: self.ui_action_open_command_file(filename))`
