### ISSUE TITLE
Command status dialog needs to be non-modal

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-geoprocessor-python#172]
The command status dialog is currently modal and does not allow interaction with the main UI while it is shown.  The dialog needs to be non-modal so that the user can look at problems and then try to fix them in the main UI.

**Comment by jurentie** [comment]
Fixed this issue by making `command_status_dialog` in `show_command_status()` to `self.command_status_dialog` and changing `command_status_dialog.exec()` to `self.command_status_dialog.show()`
