### ISSUE TITLE
Cannot view tables from ReadTableFrom...() commands

### ISSUE THREAD

**Issue by kswaim** [OpenWaterFoundation/owf-app-geoprocessor-python#203]
With both of the ReadTableFromDelimitedFile() and ReadTableFromExcel() commands, the commands appear to run fine (no errors are given), but it is not possible to view the output table.  Clicking on the table name or right-clicking on the name do not open the table.

**Comment by smalers** [comment]
I fixed this issue in #363.  Close this issue.
