### ISSUE TITLE
Command editor refresh_command should use AbstractCommand to create command string

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-geoprocessor-python#235]
The `SimpleCommandEditor.refresh_command()` method is constructing the command string.  This is redundant with `AbstractCommand.to_string()` method.  The `refresh_command` method should extract the parameter values from UI components and put into a dictionary and then pass to the command `to_string` method.  Justin should take a cut at this after cleanup up the UI code and I would like to review.

**Comment by jurentie** [comment]
This has been fixed by Steve in touching up the design of the command editors.
