### ISSUE TITLE
Saving a command file the first time has incorrect relative paths for files

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-geoprocessor-python#255]
The design should be that any input or output file that is specified in a command parameter will use a path relative the the command file folder.  This allows the command file and its referenced input and output files to be packaged and transported between computers.

However, editing a command with input or output file from a new session appears to be using the user's home folder location to compute the relative path for the selected files.  This may result in the relative path being `../../../../something`, when it should just be `something`.

Check TSTool to see how it behaves but TSTool may not deal with this well either.  It may be necessary to warn the user at an appropriate time with a message like "File paths by default are relative to the command file location.  However, the command file has not yet been saved.  Please save the command file before specifying filenames in commands."

This could possibly be checked by a None working directory coming back, or check whether the working directory matches the user files folder (both should be application properties or properties on the processor).

Ideally we don't want to put checks all over the place because really we want the user to save a command file, even if no lines or with a single comment, and then everything works OK with relative paths.

**Comment by jurentie** [comment]
To avoid this issue and not have to add a ton of code checking different scenarios it might be best to prompt user to save a new command file when they are opening a file path in the command editor.

**Comment by jurentie** [comment]
To avoid this issue I have added a check to see if the command file has been saved when the user clicks on file search. If the command has not been saved then prompt the user to ask if they would like to save the file to prevent any issues with relative paths. If they decline then they will get a warning message saying that this might create unwanted behavior with path names.
