### ISSUE TITLE
RemoveFile raises a warning when IfSourceFileNotFound parameter is set to `IGNORE`

### ISSUE THREAD

**Issue by egiles16** [OpenWaterFoundation/owf-app-geoprocessor-python#36]
The `RemoveFile` command is used for nearly every GeoProcessor test. I have noticed that even when the `IfSourceFileNotFound` parameter is set to `IGNORE`, a warning is still logged when the file is not found. This is not a crucial bug for the warning does not cause the test to break. It is, however, a visual nuisance when running the tests.

**Comment by smalers** [comment]
This was previously fixed.  Close the issue.
