### ISSUE TITLE
Enable all commands in UI command menus

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-geoprocessor-python#84]
Need to enable command menus for all commands that have been developed.  This will expose users to those commands so they are not hidden in the processor.  The menus should be organized in the general order of create/read, process, output, with other specialty command groups at the bottom.  See TSTool for an example of how to do.  The following comments apply:

1. Ideally, a minimal number of menu layers should be used.  TSTool uses two layers, which seems to work well.  The existing GeoProcessor is using 3+ menu layers, which is probably too much and shoudl be refactored to be more like TSTool.  It may be necessary to move the table commands to a separate menu like in TSTool.  This was done in TSTool mainly because the main Commands menu was getting so long that it could not fit vertically on the screen.
2. Each menu should display the command editor for the corresponding command, similar to TSTool.
3. By default, a general editor should be displayed.   See the TSTool default command editor when a specific command editor is not known.  However, in TSTool a general text editor is used for the command.  In the GeoProcessor, a parameter/value editor should be used.
4. A decision needs to be made as to whether the commands are added to the menu in a hard-coded way, or should a dictionary/list of commands be defined somewhere with menu group, menu label, etc.  It may be possible to get a list of commands from the command factory or processor class, but need to keep the processor and UI code relationship should be kept decoupled if possible (so that batch runs can occur).
5. At some point, plugin commands will be enabled to allow user-defined logic.  TSTool has started this.  This should not drive the initial design but will come into play at some point.  Plugin commands need a way to configure where the menu will be added, and connecting to the editor code.

Once the basic menu implementation is in place, we can troubleshoot the generic editor design and add specific editors if necessary.

**Comment by jurentie** [comment]
This has been taken care of. Closing issue.
